server:
  port: 8888
eureka:
  instance:
    hostname: localhost
  client:
    ##\u9632\u6B62\u81EA\u5DF1\u88AB\u6CE8\u518C
    registerWithEureka: false
    ##\u83B7\u53D6\u6CE8\u518C\u5217\u8868
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

